spring:
  datasource:
    username: blog
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server-ip}:3306/stack?characterEncoding=utf-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: iretail
mybatis:
  mapper-locations: classpath:dao/*Dao.xml
  type-aliases-package: com.example.iretail.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
controller:
  path: com.example.iretail.controller
permission:
  update: true

jwt:
  token:
    secret: test
    # 30m
    expTime: 1800000
